title: Unisys12's Blog
author: unisys12
email: unisys12@gmail.com
description: Personal Blog of a Hobbiest Web Developer and Gamer
twitter_username: unisys12
github_username:  unisys12

# Build settings
markdown: kramdown
